=== webtech-uos/nodejs-lrs/app/validator/schemas/Statement.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id" : "Statement#",
  "description": "schema for a statement object in the xAPI without restricted properties, version 1.0.*",
  "type": "object",
  "properties": {
    "id" : {
      "$ref" : "UUID"
    },
    "actor" : {
      "oneOf" : [ 
        { "$ref" : "Agent" },
        { "$ref" : "Group" }
      ]
    },
    "verb" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "$ref" : "IRI"
        },
        "display" : {
          "$ref" : "LanguageMap"
        },
        "name" : {
          "$ref" : "LanguageMap"
        },
        "description" : {
          "$ref" : "LanguageMap"
        }
      },
      "additionalProperties" : false,
      "required" : ["id"]
    },
    "object" : {
      "$ref" : "Object"
    },
    "timestamp" : {
      "$ref" : "ISO8061Date"
    },
    "stored" : {
      "$ref" : "ISO8061Date"
    },
    "authority" : {
      "oneOf" : [{ 
        "$ref" : "Agent" 
      },{ 
        "allOf" : [{
          "$ref" : "Group#/definitions/AnonymousGroup"
        },{
          "properties" : { 
            "member" : {
              "type" : "array",
              "minItems" : 2,
              "maxItems" : 2
            }
          }
        }]
      }]
    },
    "version" : {
      "type" : "string",
      "pattern" : "^1\\.0\\.\\d+$"
    },
    "attachments" : {
      "type" : "array",
      "items" : {
        "$ref" : "Attachment"
      }
    },
    "result" : {
      "$ref" : "Result"
    },
    "context" : {
      "$ref" : "Context"
    }
  },
  "required" : ["actor", "verb", "object"]
}

=== webtech-uos/nodejs-lrs/app/validator/test.json
{
   "actor": {
       "name": "Sally Glider",
       "mbox": "mailto:sally@example.com"
    },
     "verb": {
         "id": "http://adlnet.gov/expapi/verbs/completed",
         "display": {"en-US": "completed"}
    },
    "object": {
        "id": "http://example.com/activities/hang-gliding-test",
        "definition": {
            "type": "assessment",
            "name": { "en-US": "Hang Gliding Test" },
    "description": { "en-US": "The Solo Hang Gliding test, consisting of a timed flight from the peak of Mount Magazine" },
            "extensions": {
                "http://example.com/gliderClubId": "test-435"
            }
        }
    },
    "result": {
        "completion": true,
        "success": true,
        "score": {
            "scaled": 0.95
        },
        "extensions": {
            "http://example.com/flight/averagePitch": 0.05
        }
    },
    "context": {
        "instructor": {
            "name": "Irene Instructor",
            "mbox": "mailto:irene@example.com"
         },
         "contextActivities":{
             "parent": { "id": "http://example.com/activities/hang-gliding-class-a" },
             "grouping": { "id": "http://example.com/activities/hang-gliding-school" }
         },
        "extensions": {
            "http://example.com/weatherConditions": "rainy"
        }
    },
    "timestamp": "2012-07-05T18:30:32.360Z",
    "stored": "2012-07-05T18:30:33.540Z",
    "authority": {
        "name": "Irene Instructor",
        "mbox": "mailto:irene@example.com"
    }
}

=== webtech-uos/nodejs-lrs/test/data/1.0.0/valid/statement/minimal-example-variants/minimal-agent-account.json
{
  "id": "12345678-1234-5678-1234-567812345678",
  "actor":{
    "account": {
        "homePage": "http://www.example.com",
        "name": "1625378"
    }
  },
  "verb":{
    "id":"http://adlnet.gov/expapi/verbs/created",
    "display":{
       "en-US":"created"
    }
  },
  "object":{
    "id":"http://example.adlnet.gov/xapi/example/activity"
  }
}

=== webtech-uos/nodejs-lrs/test/data/1.0.0/valid/statement/minimal-example-variants/minimal-agent-group-identified-nomembers.json
{
  "id": "12345678-1234-5678-1234-567812345678",
  "actor":{
    "objectType":"group",
    "name":"Universität Osnabrück, Participants Web-Technologien II, Wintersemester 2013/2014",
    "mbox":"mailto:test@uos.de"
  },
  "verb":{
    "id":"http://adlnet.gov/expapi/verbs/created",
    "display":{
       "en-US":"created"
    }
  },
  "object":{
    "id":"http://example.adlnet.gov/xapi/example/activity"
  }
}

=== webtech-uos/nodejs-lrs/test/data/1.0.0/valid/statement/minimal-example-variants/minimal-agent-group-identified-members.json
{
  "id": "12345678-1234-5678-1234-567812345678",
  "actor":{
    "objectType":"group",
    "name":"Universität Osnabrück, Participants Web-Technologien II, Wintersemester 2013/2014",
    "mbox":"mailto:test@uos.de",
    "member":[
        {"objectType":"agent", "mbox":"mailto:test@test.test"},
        {"name":"Martin", "openid":"http://martin.test/martin"},
        {"account":{ 
           "homePage":"demo.studip.de",
           "name":"test_autor"
        }}
    ]
  },
  "verb":{
    "id":"http://adlnet.gov/expapi/verbs/created",
    "display":{
       "en-US":"created"
    }
  },
  "object":{
    "id":"http://example.adlnet.gov/xapi/example/activity"
  }
}
